--- # PATS configuration
domain:
  lat_0: 50.629609  # Latitude of SW corner of domain
  lon_0: 17.425667  # Longitude of SW corner of domain
  spacing: 1000.0   # grid spacing in meters
  ni: 100           # number of gridpoints in w-e axis 
  nj: 100           # number of gridpoints in s-n axis
timestep: 1.0       # model timestep in seconds 
level_type: "model" # type of level to be read from data files
data_files:         # list of files with environment data
  - "./data/era5_model.grib"
threads: 16         # number of threads the model should use
memory: 8196        # memory available for model in MB
