--- # PATS configuration

# For more information how to set up this config file
# check the configuration module documentaiton

domain:
  ref_lat: 49.00                # Latitude of SW corner of domain
  ref_lon: 14.00                # Longitude of SW corner of domain
  spacing: 2500.0               # grid spacing in meters
  shape: [300, 270]             # lon-lat shape of domain (in number of model gridpoints)
datetime:
  start: "2021-06-24T06:00:00"
  timestep: 1.0                 # model timestep in seconds
input:
  level_type: "isobaricInhPa"   # type of level to be read from data files
  data_files:                   # list of files with environment and surface data
    - "./data/era5_pl.grib"
    - "./data/era5_surface.grib"
resources:    
  threads: 8                    # number of threads the model should use
  memory: 8196                  # memory cap for model in MB
