# This is a basic workflow to help you get started with Actions

name: build-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install necessary libs
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install clang
          sudo apt-get install libclang1
          sudo apt-get install libeccodes-dev
          rustup update stable
          cargo install mdbook
          cargo clean
          mkdir docs-out
      
      # Build technical documentation
      - name: Build doc
        run: |
          cargo doc --target-dir "docs-out"
          rm -rf docs-out/debug
      
      # Build guidebook
      - name: Build guide
        run: mdbook build --dest-dir ../docs-out/guidebook ./guide
        
      # Push to docs repository
      - name: Push to repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs-out'
          destination-github-username: 'Quba1'
          destination-repository-username: 'pats-model'
          destination-repository-name: 'pats-docs'
          user-email: 'scaleweather@gmail.com'
          target-branch: 'main'
          target-directory: 'docs'
